### ISSUE TITLE
the wordlist every entry in it starts with ' ... why ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [Paradoxis/Flask-Unsign-Wordlist#5]
doesn't that make every line diff than it's supposed to be ?

**Comment by Paradoxis** [comment]
@minanagehsalalma some secrets contain binary characters, which include newlines, which cannot be stored in a newline delimited wordlist because splitting on `\n` would result in an incorrect secret being attempted. So using a function like Python's `ascii(...)` helps escape these characters, which can then be stored in a file without the risk of newlines polluting the file. 

They're loaded and parsed on runtime using Python's [literal_eval](https://docs.python.org/3/library/ast.html#ast.literal_eval) function to guarantee the secret is what it's supposed to be. You can suppress this behavior in the main tool using the `--no-literal-eval` flag

So no, it doesn't cause the secrets to be different. If anything it ensures correctness.
